name: Compilar APK para Amazon Appstore (Flet)

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build-android:
    runs-on: ubuntu-latest

    steps:
      - name: Descargar repositorio
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Configurar Java JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Instalar Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Instalar dependencias del sistema y Python
        run: |
          sudo apt-get update -y
          sudo apt-get install -y ninja-build libgtk-3-dev
          pip install --upgrade pip
          pip install flet openpyxl pillow

      - name: Generar Keystore de Release para Amazon
        run: |
          keytool -genkey -v -keystore release.jks -keyalg RSA -keysize 2048 -validity 10000 -alias amazonkey -dname "CN=LZ79 Essential, OU=App, O=LZ79, L=Madrid, C=ES" -storepass 12345678 -keypass 12345678
          echo "KEYSTORE_PASS=12345678" >> $GITHUB_ENV
          echo "KEY_ALIAS=amazonkey" >> $GITHUB_ENV
          echo "KEY_PASS=12345678" >> $GITHUB_ENV

      - name: Compilar APK con Flet
        run: |
         flet build apk --project "LZ79 Essential" --org com.lz79freelance

      - name: Guardar APK como artefacto
        uses: actions/upload-artifact@v4
        with:
          name: LZ79-Essential-Amazon-APK
          path: build/apk/*.apk
